spring:
  liquibase:
    change-log: classpath:changelogs/changelog-master.yaml
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/api_paystack}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
